"""Add a manually curated (SMILES, TARGET) CSV as a new property in the
LoQI ThermoGen mirror, complete with 5-fold random + scaffold splits.

Mirrors the splitting logic of upstream scripts/build_final_db_strict.py
(same SEED=42, VALID_FRACTION=0.1, Bemis-Murcko scaffolds, 12-element strict
filter) so the new property plugs into run_cv.sh exactly like a property
generated by the regular pipeline.

Writes:
  Clean/<prop>.csv                                    (SMILES, TARGET)
  per_property/<prop>.csv                             (inchikey,smiles,value,tier,scaffold)
  <prop>/random_5fold.json + scaffold_5fold.json
  csv_data/<prop>/Split/{random_cv5,scaffold_cv5}/cv{1-5}_{train,valid,test}.csv
  Split/<prop>/{random_cv5,scaffold_cv5}              (relative symlinks)
  distributions/<prop>.png                            (matplotlib histogram)
  splits_summary.csv                                  (appends one row)

Usage:
  python scripts/add_manual_property.py \
      --src /Users/zhao922/Desktop/Data_20260515_Vcp.csv \
      --prop visc_liq_298K_cP_manual \
      --root downstream_ft/0515_final

Idempotent: re-running with the same --prop overwrites the property's
artifacts and rewrites its splits_summary row.
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import random
from collections import defaultdict
from pathlib import Path

from rdkit import Chem
from rdkit import RDLogger
from rdkit.Chem.Scaffolds import MurckoScaffold

RDLogger.DisableLog('rdApp.*')

SEED = 42
N_FOLDS = 5
VALID_FRACTION = 0.1
ALLOWED_ELEMENTS = {'C', 'H', 'O', 'N', 'P', 'S', 'F', 'Cl', 'Br', 'I', 'Si', 'B'}


def canonicalize(smi: str):
    try:
        m = Chem.MolFromSmiles(smi)
        if m is None:
            return None, None
        smi_iso = Chem.MolToSmiles(m, isomericSmiles=True)
        ik = Chem.inchi.MolToInchiKey(m)
        return smi_iso, ik
    except Exception:
        return None, None


def element_filter(smi: str):
    m = Chem.MolFromSmiles(smi)
    if m is None:
        return False, 'invalid_smiles'
    atoms = list(m.GetAtoms())
    if Chem.GetFormalCharge(m) != 0:
        return False, 'charged'
    if any(a.GetNumRadicalElectrons() > 0 for a in atoms):
        return False, 'radical'
    bad = next((a.GetSymbol() for a in atoms if a.GetSymbol() not in ALLOWED_ELEMENTS), None)
    if bad:
        return False, f'non_loqi_{bad}'
    return True, 'ok'


def get_scaffold(smi: str):
    m = Chem.MolFromSmiles(smi)
    if m is None:
        return None
    return (MurckoScaffold.MurckoScaffoldSmiles(mol=m, includeChirality=False)
            or 'EMPTY_SCAFFOLD')


def random_kfold(n, k, seed):
    idx = list(range(n))
    rng = random.Random(seed)
    rng.shuffle(idx)
    return [idx[i::k] for i in range(k)]


def scaffold_kfold(scaffolds, k, seed):
    groups = defaultdict(list)
    for i, s in enumerate(scaffolds):
        groups[s].append(i)
    items = sorted(groups.values(), key=lambda g: (-len(g), g[0]))
    folds = [[] for _ in range(k)]
    for grp in items:
        smallest = min(range(k), key=lambda j: len(folds[j]))
        folds[smallest].extend(grp)
    rng = random.Random(seed)
    for f in folds:
        rng.shuffle(f)
    return folds


def sample_valid(train_idx, valid_frac, seed_per_fold):
    rng = random.Random(seed_per_fold)
    shuffled = list(train_idx)
    rng.shuffle(shuffled)
    n_val = max(1, int(round(len(shuffled) * valid_frac)))
    return sorted(shuffled[n_val:]), sorted(shuffled[:n_val])


def emit_fold_csvs(items, kfolds, out_dir):
    """items = list of (ik, smi, scaffold, value)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    fold_meta = []
    for k_idx, test_idx in enumerate(kfolds, 1):
        test_set = set(test_idx)
        train_all = [i for i in range(len(items)) if i not in test_set]
        train_idx, valid_idx = sample_valid(train_all, VALID_FRACTION, SEED + k_idx)
        fold_meta.append({'train_idx': train_idx, 'valid_idx': valid_idx,
                          'test_idx': sorted(test_idx)})
        for tag, idxs in (('train', train_idx),
                          ('valid', valid_idx),
                          ('test', sorted(test_idx))):
            with open(out_dir / f'cv{k_idx}_{tag}.csv', 'w', newline='') as fp:
                w = csv.writer(fp)
                w.writerow(['SMILES', 'TARGET'])
                for i in idxs:
                    _, smi, _, val = items[i]
                    w.writerow([smi, val])
    return fold_meta


def make_symlink(target_dir, link_path):
    """Create relative symlink link_path → target_dir, replacing if needed."""
    if link_path.is_symlink() or link_path.exists():
        if link_path.is_symlink() or link_path.is_file():
            link_path.unlink()
        else:
            import shutil
            shutil.rmtree(link_path)
    rel = os.path.relpath(target_dir, link_path.parent)
    link_path.symlink_to(rel)


def update_splits_summary(root, prop, n_mol, n_scaffolds, rfolds, sfolds):
    p = root / 'splits_summary.csv'
    rows = []
    fieldnames = ['property', 'n_molecules', 'n_scaffolds',
                  'random_fold_sizes', 'scaffold_fold_sizes']
    if p.exists():
        for r in csv.DictReader(p.open()):
            if r['property'] != prop:
                rows.append(r)
    rows.append({
        'property': prop,
        'n_molecules': n_mol,
        'n_scaffolds': n_scaffolds,
        'random_fold_sizes': '|'.join(str(len(f)) for f in rfolds),
        'scaffold_fold_sizes': '|'.join(str(len(f)) for f in sfolds),
    })
    rows.sort(key=lambda r: r['property'])
    with p.open('w', newline='') as fp:
        w = csv.DictWriter(fp, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)


def plot_distribution(prop, values, dist_dir):
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
    except ImportError:
        return False
    dist_dir.mkdir(parents=True, exist_ok=True)
    n = len(values)
    if n == 0:
        return False
    m = sum(values) / n
    s = (sum((v - m) ** 2 for v in values) / n) ** 0.5 if n > 1 else 0.0
    logy = prop.startswith('visc') or 'dielectric' in prop or 'Q_' in prop
    fig, ax = plt.subplots(figsize=(6, 3.5))
    ax.hist(values, bins=min(60, max(10, n // 50)),
            color='#4a7bb7', edgecolor='white', linewidth=0.5)
    if logy:
        ax.set_yscale('log')
    ax.set_title(f'{prop}  (n={n}, μ={m:.3g}, σ={s:.3g})')
    ax.set_xlabel('value'); ax.set_ylabel('count'); ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(dist_dir / f'{prop}.png', dpi=110)
    plt.close(fig)
    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--src', required=True, help='Path to source CSV (SMILES,TARGET).')
    ap.add_argument('--prop', required=True, help='Property name to register.')
    ap.add_argument('--root', default='downstream_ft/0515_final',
                    help='LoQI mirror root.')
    ap.add_argument('--tier', default='manual',
                    help='Tier label to write in per_property/<prop>.csv (default: manual).')
    ap.add_argument('--smiles-col', default='SMILES')
    ap.add_argument('--target-col', default='TARGET')
    args = ap.parse_args()

    src = Path(args.src).expanduser().resolve()
    root = Path(args.root).resolve()
    prop = args.prop

    if not src.exists():
        raise SystemExit(f'ERROR: source {src} not found')
    if not (root / 'per_property').is_dir():
        raise SystemExit(f'ERROR: {root}/per_property missing — not a valid mirror')

    # --- 1. Load + filter ---
    print(f'Reading {src}')
    n_raw = n_invalid = n_bad_elem = n_dup = n_bad_value = 0
    elem_reasons = defaultdict(int)
    seen_ik = set()
    items = []  # (ik, smi_iso, scaffold, value)
    for r in csv.DictReader(src.open()):
        n_raw += 1
        smi_raw = r.get(args.smiles_col, '').strip()
        tgt_raw = r.get(args.target_col, '').strip()
        if not smi_raw or not tgt_raw:
            n_invalid += 1; continue
        smi_iso, ik = canonicalize(smi_raw)
        if not smi_iso:
            n_invalid += 1; continue
        ok, reason = element_filter(smi_iso)
        if not ok:
            n_bad_elem += 1; elem_reasons[reason] += 1; continue
        try:
            val = float(tgt_raw)
        except ValueError:
            n_bad_value += 1; continue
        if ik in seen_ik:
            n_dup += 1; continue
        seen_ik.add(ik)
        items.append((ik, smi_iso, get_scaffold(smi_iso), val))

    n = len(items)
    print(f'  raw={n_raw}  kept={n}  invalid={n_invalid}  '
          f'bad_elem={n_bad_elem}  dup_ik={n_dup}  bad_value={n_bad_value}')
    if elem_reasons:
        print(f'  element reasons: {dict(elem_reasons)}')
    if n < 50:
        raise SystemExit(f'ERROR: only {n} valid rows — too few for 5-fold CV')

    # --- 2. Compute splits ---
    rfolds = random_kfold(n, N_FOLDS, SEED)
    sfolds = scaffold_kfold([s for _, _, s, _ in items], N_FOLDS, SEED)
    n_scaffolds = len(set(s for _, _, s, _ in items))
    print(f'  random fold sizes:   {[len(f) for f in rfolds]}')
    print(f'  scaffold fold sizes: {[len(f) for f in sfolds]}')
    print(f'  unique scaffolds:    {n_scaffolds}')

    # --- 3. Write Clean/<prop>.csv ---
    clean_dir = root / 'Clean'; clean_dir.mkdir(exist_ok=True)
    with (clean_dir / f'{prop}.csv').open('w', newline='') as fp:
        w = csv.writer(fp); w.writerow(['SMILES', 'TARGET'])
        for _, smi, _, val in items:
            w.writerow([smi, val])
    print(f'  wrote Clean/{prop}.csv')

    # --- 4. Write per_property/<prop>.csv ---
    pp_dir = root / 'per_property'
    with (pp_dir / f'{prop}.csv').open('w', newline='') as fp:
        w = csv.DictWriter(fp, fieldnames=['inchikey', 'smiles', 'value', 'tier', 'scaffold'])
        w.writeheader()
        for ik, smi, scaf, val in items:
            w.writerow({'inchikey': ik, 'smiles': smi, 'value': val,
                        'tier': args.tier, 'scaffold': scaf})
    print(f'  wrote per_property/{prop}.csv')

    # --- 5. Emit per-fold csvs + JSON metadata ---
    prop_dir = root / prop; prop_dir.mkdir(exist_ok=True)
    csv_split = root / 'csv_data' / prop / 'Split'
    rfold_meta = emit_fold_csvs(items, rfolds, csv_split / 'random_cv5')
    sfold_meta = emit_fold_csvs(items, sfolds, csv_split / 'scaffold_cv5')
    molecules = [{'inchikey': ik, 'smiles': smi} for ik, smi, _, _ in items]
    for meta_name, kfolds, fold_meta in (('random_5fold.json', rfolds, rfold_meta),
                                          ('scaffold_5fold.json', sfolds, sfold_meta)):
        with (prop_dir / meta_name).open('w') as fp:
            json.dump({
                'method': 'random_kfold' if 'random' in meta_name else 'scaffold_kfold',
                'k': N_FOLDS, 'seed': SEED, 'n_total': n,
                'folds': fold_meta,
                'molecules': molecules,
                'valid_split': {'source': 'train_idx',
                                'fraction_of_original_train': VALID_FRACTION,
                                'seed': SEED,
                                'strategy': 'deterministic random sample per property/split/fold'},
            }, fp, indent=2)
    print(f'  wrote {prop}/random_5fold.json + scaffold_5fold.json')
    print(f'  wrote csv_data/{prop}/Split/{{random,scaffold}}_cv5/cv*.csv')

    # --- 6. Split/<prop>/{random_cv5,scaffold_cv5} symlinks ---
    split_dir = root / 'Split' / prop; split_dir.mkdir(parents=True, exist_ok=True)
    make_symlink(csv_split / 'random_cv5',   split_dir / 'random_cv5')
    make_symlink(csv_split / 'scaffold_cv5', split_dir / 'scaffold_cv5')
    print(f'  wrote Split/{prop}/{{random_cv5,scaffold_cv5}} symlinks')

    # --- 7. distribution PNG ---
    if plot_distribution(prop, [v for _, _, _, v in items], root / 'distributions'):
        print(f'  wrote distributions/{prop}.png')

    # --- 8. update splits_summary.csv ---
    update_splits_summary(root, prop, n, n_scaffolds, rfolds, sfolds)
    print(f'  updated splits_summary.csv')

    print(f'\nDone. Property `{prop}` ({n} mols, {n_scaffolds} scaffolds) '
          f'added to {root}.')


if __name__ == '__main__':
    main()
